<a href="https://colab.research.google.com/github/a08037/-/blob/main/Simulative_%D0%9F%D0%BE%D0%B4%D0%B1%D0%BE%D1%80%D0%BA%D0%B0_%D1%81%D0%BE%D0%B2%D0%B5%D1%82%D0%BE%D0%B2_%D0%BF%D0%BE_%D1%83%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%BD%D0%B8%D1%8E_%D0%BA%D0%BE%D0%B4%D0%B0_%D0%B2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ряд операций в коммерческом коде при обычном написании могут выглядеть достаточно громоздко и плохо читаемо. Это можно исправить за счет грамотного использования скобок, чему и будет посвящена первая часть нашей подборки.

# 1. Распаковка списка с помощью кортежа и скобок

Допустим, нам необходимо распаковать кортеж

In [ ]:
meats = ["chichken", "fish"]

In [ ]:
a, b = meats

print(a)
print(b)

chichken
fish

Использование коротких названий переменных не приветствуется. Вместо этого используются более длинные, но более информативные названия. Обработать их можно с помощью кортежа и скобок

In [ ]:
(
    chicken_meat,
    fish_meat
) = meats

print(chicken_meat)
print(fish_meat)

chichken
fish

Таким образом, мы можем использовать скобки для помощи в распаковке кортежей

Обратите внимание, что благодаря этому наша распаковка кортежей может вместить гораздо более длинные и более описательные имена переменных.

# 2. Логические условия со скобками

Допустим, у нас есть оператор if с 3 условиями, объединенными с помощью ключевого слова and.

In [ ]:
condition1, condition2, condition3 = True, True, True

if condition1 and condition2 and condition3:
    print("All conditions are True")

All conditions are True

В рабочем коде условия становятся длиннее, и может быть больше условий. Поэтому один из способов решения этой проблемы - рефакторинг этого гигантского условия в отдельную функцию.
Или, если мы решим, что нет необходимости писать новую функцию только для этого, мы можем записать наши условные выражения, используя скобки.

In [ ]:
if (
    condition1
    and condition2
    and condition3
    ):
    print("All conditions are True")

All conditions are True

Таким образом, мы не вынуждены писать новую функцию или переменную только для этого одного условного выражения, и при этом мы можем сохранить его аккуратным и читаемым.

# 3. Комбинирование строк с помощью скобок

Строки производственного уровня обычно не помещаются в одну строку из-за своей многословности. Поэтому мы объединяем их с помощью скобок.

In [ ]:
RETRY_INTERVAL = 10
var1 = "var1"
var2 = "var2"

error_log_message = (
    "ERROR. Failed to perform computaion"
    f"on {var1} and {var2}."
    f"Retrying in {RETRY_INTERVAL} seconds."
)

error_log_message

'ERROR. Failed to perform computaionon var1 and var2.Retrying in 10 seconds.'

Примечание — внутри скобок строковые литералы, заключенные в кавычки, автоматически складываются, и нам не нужно использовать оператор + для этого.

# 4. Многострочное связывание методов с помощью скобок

В промышленном коде названия методов обычно намного длиннее, и мы часто связываем вместе больше методов.

И снова, мы используем скобки, чтобы разместить весь этот код на нескольких строках, вместо того чтобы сокращать названия методов или переменных.

In [ ]:
import pandas as pd

df = pd.DataFrame({"group_id": [1, 1, 2, 2], "name": ["Anton", "Elmira", "Sergey", "Elena"]})
df

   group_id    name
0         1   Anton
1         1  Elmira
2         2  Sergey
3         2   Elena

In [ ]:
df.groupby(by=["group_id"]).agg({"name": "nunique"}).reset_index().sort_values(by="name", ascending=False)

   group_id  name
0         1     2
1         2     2

Обратите внимание, что если мы выполняем цепочку методов внутри скобок, нам не требуется использовать символ \ для явного разрыва строки.

In [ ]:
output = (
    df
    .groupby(by=["group_id"])
    .agg({"name": "nunique"})
    .reset_index()
    .sort_values(by="name", ascending=False)
)
output

   group_id  name
0         1     2
1         2     2